const actions = {
    GET_PRODUCTS: "GET_PRODUCTS",
    GET_WISHES: "GET_WISHES",
    GET_CATEG: "GET_CATEG",
    REMOVE_WISH: "REMOVE_WISH",
    GET_SHOPPING: "GET_SHOPPING",
    REMOVE_SHOPPING: "REMOVE_SHOPPING",
    UPDATE__COUNT: "UPDATE__COUNT",
    GET_SEARCHING: "GET_SEARCHING",
    GET_WISHES_LOCALSTORAGE: "GET_WISHES_LOCALSTORAGE",
    GET_SHOPPING_LOCALSTORAGE: "GET_SHOPPING_LOCALSTORAGE",
    GET_SEARCHING_LOCALSTORAGE: "GET_SEARCHING_LOCALSTORAGE",
    CHANGE_LOADING: "CHANGE_LOADING",
    GET_NOVAS_PRODUCTS: "GET_NOVAS_PRODUCTS",
    GET_SALES_PRODUCTS: "GET_SALES_PRODUCTS"
};

export default actions;